
name: Build test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependancies
      run: npm ci
    - run: npm run build --if-present
    - name: Run tests
      run: npm run test:unit
    -name: Display Softuni username
      run: echo "Laura696921"
